### ISSUE TITLE
Why is installation from PSGallery deprecated?

### ISSUE THREAD

**Issue by bergmeister** [liuzijing97/scoop-auto-completion#8]
The readme says that installing via PSGallery is deprecated. Why?
I am at the moment creating a meta module for all PS module that offer tab completion help and consider adding scoop-completion. My bootstrapper is entirely based on the PSGallery and I don't want to maintain custom commands for installing each module, hence my question.

**Comment by Lockszmith-GH** [comment]
I can't answer for @Moeologist the maintainer of the code, but I was the one who suggested that auto completion for scoop be native to scoop via issue #4 .

I'm assuming liuzijing97 would rather maintain one point, and since this is tied specifically to scoop, it makes total sense to activate it through scoop as well.

I wonder if this is a clash of wants - you not wanting to maintain something specific on your end, and this now wanting to maintain multiple points.

When the scoop method of installing was introduced, I ended up creating 2 [scoop aliases](https://github.com/liuzijing97/scoop-completion/issues/4#issuecomment-510185998) for enabling and disabling autocomplete, this has worked well for me.

###### EDIT: changed mention from liuzijing97 to Moeologist.

**Comment by bergmeister** [comment]
Thanks for the info.
The problem here is that the installation source is not very robust, it depends on the existence of a file in this GitHub repo. If something is published on the PSGallery or other artifact repositories, then they do not allow deletion and therefore consumers are safe from someone accidentally breaking the food chain. Taking a dependency on the PSGallery is much better as the Gallery guarantees the existence of the package.
I don't mind if completion is native via scoop but then in this case, the PowerShell module should just ship the `scoop-completion.json` file and have a simple command that runs `scoop install scoop-completion.json`, this way the package would be self contained and safely stored on the PSGallery.
I don't mind doing that myself but this repo has not declared a licence...

**Comment by Lockszmith-GH** [comment]
That's a neat idea, maybe that's what Moeologist will choose to do, a response will most likely come soon and we'll see where this blows.

###### EDIT: changed mentioned username from liuzijing97 to Moeologist.

**Comment by Moeologist** [comment]
At first the installation only support PSGallery. I add a scoop manifest later because I think scoop users perfer this. For a Readme, the simple the better. Actually, scoop increases the complexity of installation. (I don't know much about scoop, changing profile silently is not a good idea.)
If you just think "scoop install [remote file]" was awful, I'll revise Readme according to #6 #7 .
However, the manifest was not neat indeed. It based on master branch and throw a warning after installing. Any suggestion is welcome.
BTW, I prefer to install PSModule via PSGet. I'm glad to keep this.
My English is not that good. I hope I express my meaning properly.
